{{- if eq (include "headplane.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "headplane.secretName" . }}
  labels:
    {{- include "headplane.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.cookieSecret }}
  {{ .Values.secrets.cookieSecretKey }}: {{ .Values.secrets.cookieSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.apiKey }}
  {{ .Values.secrets.apiKeyKey }}: {{ .Values.secrets.apiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.clientSecret }}
  {{ .Values.secrets.clientSecretKey }}: {{ .Values.secrets.clientSecret | quote }}
  {{- end }}
{{- end }}
